version: '3.8'
services:
    app:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
            - "9229:9229"
        networks:
            - app-network
        restart: unless-stopped
        depends_on:
            - mongodb
        env_file:
            - .env
    mongodb:
        container_name: mongodb
        image: mongo:latest
        env_file:
            - .env
        ports:
            - "27017:27017"
        networks:
            - app-network
        restart: unless-stopped
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/app --quiet
            interval: 30s
            timeout: 10s
            retries: 5
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.13.0-management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - app-network
        restart: unless-stopped
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/app --quiet
            interval: 30s
            timeout: 10s
            retries: 5

networks:
    app-network: