version: '3.8'
services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run start:debug
        ports:
            - "3000:3000"
            - "9229:9229"
        networks:
            - app-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - mongodb
        environment:
            MONDODB_URI: mongodb://root:root@mongodb:27017/app
    mongodb:
        container_name: mongodb
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - "27017:27017"
        networks:
            - app-network
        restart: unless-stopped
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/app --quiet
            interval: 30s
            timeout: 10s
            retries: 5

networks:
    app-network: